# Generated by Django 5.1.3 on 2024-11-24 12:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900, 'Год не может быть меньше 1900'), django.core.validators.MaxValueValidator(2024, 'Год не может быть больше текущего')])),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('color', models.CharField(max_length=30)),
                ('volume', models.FloatField()),
                ('type_change', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('marka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.marka')),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=32)),
                ('marka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.marka')),
            ],
        ),
    ]
